name: bmi
description: BMI Calculator to learn about State Management.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.0.1
  flutter:
    sdk: flutter
  flutter_web_router: ^1.0.2
  intl: ^0.17.0
  syncfusion_flutter_gauges: ^19.2.46

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
